* Advent of Code - 2024.
https://adventofcode.com/2024

** Common.

#+BEGIN_SRC lisp
(ql:quickload "cl-ppcre")
(ql:quickload "alexandria")
(ql:quickload "cl-interpol")
#+END_SRC

#+RESULTS:
| cl-interpol |

** Day 1.
https://adventofcode.com/2024/day/1

*** Part 1.

#+BEGIN_SRC lisp
(defun total-dist (file-name)
  "Finds the total distance between pairs in two lists after sorting them individually."
  (let ((left-list '()) (right-list '()))
    (with-open-file (stream file-name)
      (when (streamp stream)
        (loop for line = (read-line stream nil)
              while (stringp line)
              do
                 (let* ((words (cl-ppcre:split "\\s+" line))
                        (left-location (read-from-string (elt words 0)))
                        (right-location (read-from-string (elt words 1))))
                   (push left-location left-list)
                   (push right-location right-list)))))
    (setf left-list (sort left-list #'<))
    (setf right-list (sort right-list #'<))
    (let ((location-dist (mapcar #'abs (mapcar #'- left-list right-list))))
      (reduce #'+ location-dist))))
#+END_SRC

#+RESULTS:
: TOTAL-DIST

#+BEGIN_SRC lisp
(total-dist "inputs/day1/part1_sample.txt")
#+END_SRC

#+RESULTS:
: 11

#+BEGIN_SRC lisp
(total-dist "inputs/day1/part1_actual.txt")
#+END_SRC

#+RESULTS:
: 3246517

*** Part 2.

#+BEGIN_SRC lisp
(defun count-occurrences (list)
  "Count the number of times each item occurs in a list. Returns a hash-table containing the counts."
  (let ((counts (make-hash-table :test 'equal)))
    (loop for item in list
          do (incf (gethash item counts 0)))
    counts))

(defun similarity-score (file-name)
  "Find the similarity score between two lists."
  (let ((left-list '()) (right-list '()) counts (score 0))
    (with-open-file (stream file-name)
      (when (streamp stream) (loop for line = (read-line stream nil)
                                   while (stringp line)
                                   do (let* ((words (cl-ppcre:split "\\s+" line))
                                             (left-location (read-from-string (elt words 0)))
                                             (right-location (read-from-string (elt words 1))))
                                        (push left-location left-list)
                                        (push right-location right-list)))))
    (setf counts (count-occurrences right-list))
    (loop for item in left-list
          do (incf score (* item (gethash item counts 0))))
    score))
#+END_SRC

#+RESULTS:
: SIMILARITY-SCORE

#+BEGIN_SRC lisp
(similarity-score "inputs/day1/part2_sample.txt")
#+END_SRC

#+RESULTS:
: 31

#+BEGIN_SRC lisp
(similarity-score "inputs/day1/part2_actual.txt")
#+END_SRC

#+RESULTS:
: 29379307

** Day 2.
https://adventofcode.com/2024/day/2

*** Part 1.

#+BEGIN_SRC lisp
(defun adjacent-pairs (list)
  "Get the adjacent numbers of the list as pairs."
  (loop :for (a b) :on list
        :while (stringp b)
        :collect (mapcar #'read-from-string (list a b))))

(defun is-safe-report (list)
  "Determines if a report is 'SAFE' => elements in the list are all increasing, or all decreasing, AND, adjacent elements differ by at-least 1 and at-most 3."
  (if (< (length list) 2)
      t
      (let* ((adp (adjacent-pairs list)))
        (if
         (and (or (every #'(lambda (pair) (destructuring-bind (x y) pair
                                            (< x y)))
                         adp)
                  (every #'(lambda (pair) (destructuring-bind (x y) pair
                                            (> x y)))
                         adp))
              (every #'(lambda (pair) (destructuring-bind (x y) pair
                                        (<= 1 (abs (- x y)) 3)))
                     adp))
         t
         nil))))

(defun count-safe-reports (file-name)
  "Determines how many reports are 'SAFE'."
  (let ((num-safe-reports 0))
    (with-open-file (stream file-name)
      (when (streamp stream)
        (loop for line = (read-line stream nil)
              while (stringp line)
              do (let ((list (cl-ppcre:split "\\s+" line)))
                   (when (is-safe-report list)
                     (incf num-safe-reports))))))
    num-safe-reports))
#+END_SRC

#+RESULTS:
: COUNT-SAFE-REPORTS

#+BEGIN_SRC lisp
(count-safe-reports "inputs/day2/part1_sample.txt")
#+END_SRC

#+RESULTS:
: 2

#+BEGIN_SRC lisp
(count-safe-reports "inputs/day2/part1_actual.txt")
#+END_SRC

#+RESULTS:
: 279

*** Part 2.

#+BEGIN_SRC lisp
(defun remove-nth (list n)
  "Return the list without the nth index. Python equivalent -> list[:n] + list[n+1:]. This is a non-destructive operation."
  (if (zerop n)
      (cdr list)
      (nconc (subseq list 0 n)
             (subseq list (+ n 1)))))

(defun count-safe-reports-with-pd (file-name)
  "Determines how many reports are 'SAFE' assuming problem dampner is present."
  (let ((num-safe-reports 0))
    (with-open-file (stream file-name)
      (when (streamp stream)
        (loop for line = (read-line stream nil)
              while (stringp line)
              do (let ((list (cl-ppcre:split "\\s+" line)))
                   (if (or (is-safe-report list)
                           (loop for i below (length list)
                                   thereis (is-safe-report (remove-nth list i))))
                       (incf num-safe-reports))))))
    num-safe-reports))
#+END_SRC

#+RESULTS:
: COUNT-SAFE-REPORTS-WITH-PD

#+BEGIN_SRC lisp
(count-safe-reports-with-pd "inputs/day2/part2_sample.txt")
#+END_SRC

#+RESULTS:
: 4

#+BEGIN_SRC lisp
(count-safe-reports-with-pd "inputs/day2/part2_actual.txt")
#+END_SRC

#+RESULTS:
: 343

** Day 3.
https://adventofcode.com/2024/day/3

#+BEGIN_QUOTE
"Our computers are having issues, so I have no idea if we have any Chief Historians in stock! You're welcome to check the warehouse, though," says the mildly flustered shopkeeper at the North Pole Toboggan Rental Shop. The Historians head out to take a look.

The shopkeeper turns to you. "Any chance you can see why our computers are having issues again?"

The computer appears to be trying to run a program, but its memory (your puzzle input) is corrupted. All of the instructions have been jumbled up!

It seems like the goal of the program is just to multiply some numbers. It does that with instructions like mul(X,Y), where X and Y are each 1-3 digit numbers. For instance, mul(44,46) multiplies 44 by 46 to get a result of 2024. Similarly, mul(123,4) would multiply 123 by 4.

However, because the program's memory has been corrupted, there are also many invalid characters that should be ignored, even if they look like part of a mul instruction. Sequences like mul(4*, mul(6,9!, ?(12,34), or mul ( 2 , 4 ) do nothing.

For example, consider the following section of corrupted memory:

xmul(2,4)%&mul[3,7]!@^do_not_mul(5,5)+mul(32,64]then(mul(11,8)mul(8,5))
Only the four highlighted sections are real mul instructions. Adding up the result of each instruction produces 161 (2*4 + 5*5 + 11*8 + 8*5).

Scan the corrupted memory for uncorrupted mul instructions. What do you get if you add up all of the results of the multiplications?
#+END_QUOTE

*** Part 1.

#+BEGIN_SRC lisp
(defun extract-instructions (file-name)
  "Extract mul(x,y) instructions from the given input."
  (with-open-file (stream file-name)
    (when (streamp stream)
      (loop for corrupted = (read-line stream nil)
            while (stringp corrupted)
            summing (reduce #'+ (mapcar #'(lambda (args) (reduce #'* args))
                                        (let ((lists '())) (cl-ppcre:do-register-groups (num1 num2)
                                                               ("mul\\((\\d{1,3}),(\\d{1,3})\\)" corrupted)
                                                             (push (list (parse-integer num1) (parse-integer num2)) lists))
                                          lists)))))))
#+END_SRC

#+BEGIN_SRC lisp
(extract-instructions "inputs/day3/sample.txt")
#+END_SRC

#+RESULTS:
: 161

#+BEGIN_SRC lisp
(extract-instructions "inputs/day3/actual.txt")
#+END_SRC

#+RESULTS:
: 156388521

*** Part 2.

#+BEGIN_QUOTE
--- Part Two ---

As you scan through the corrupted memory, you notice that some of the conditional statements are also still intact. If you handle some of the uncorrupted conditional statements in the program, you might be able to get an even more accurate result.

There are two new instructions you'll need to handle:

The do() instruction enables future mul instructions.
The don't() instruction disables future mul instructions.
Only the most recent do() or don't() instruction applies. At the beginning of the program, mul instructions are enabled.

For example:

xmul(2,4)&mul[3,7]!^don't()_mul(5,5)+mul(32,64](mul(11,8)undo()?mul(8,5))
This corrupted memory is similar to the example from before, but this time the mul(5,5) and mul(11,8) instructions are disabled because there is a don't() instruction before them. The other mul instructions function normally, including the one at the end that gets re-enabled by a do() instruction.

This time, the sum of the results is 48 (2*4 + 8*5).

Handle the new instructions; what do you get if you add up all of the results of just the enabled multiplications?
#+END_QUOTE

#+BEGIN_SRC lisp
(defun extract-instructions-with-control-statements (file-name)
  "Extracts mul(x,y) instructions, along with control statements that manage state - do() and don't()."
  (let ((enabled t))
    (with-open-file (stream file-name)
      (when (streamp stream)
        (loop for corrupted = (read-line stream nil)
              while (stringp corrupted)
              summing (let ((total 0))
                         (cl-ppcre:do-register-groups (arg0 arg1 found-do found-dont)
                             (#?/mul\((\d{1,3}),(\d{1,3})\)|(do\(\))|(don't\(\))/ corrupted total)
                           (cond (found-do (setf enabled t) 0) ; found do()
                                 (found-dont (setf enabled nil) 0) ;; found don't()
                                 (t (if enabled
                                        (incf total (reduce #'* (mapcar #'parse-integer (list arg0 arg1))))
                                        0)) ; found mul(x,y)
                                 ))))))))
#+END_SRC

#+RESULTS:
: EXTRACT-INSTRUCTIONS-WITH-CONTROL-STATEMENTS

#+BEGIN_SRC lisp
(extract-instructions-with-control-statements "inputs/day3/sample.txt")
#+END_SRC

#+RESULTS:
: 161

#+BEGIN_SRC lisp
(extract-instructions-with-control-statements "inputs/day3/sample2.txt")
#+END_SRC

#+RESULTS:
: 48

#+BEGIN_SRC lisp
(extract-instructions-with-control-statements "inputs/day3/actual.txt")
#+END_SRC

#+RESULTS:
: 75920122
